name: dart_notification_center
description: A wrapper for the observer pattern for Dart in the style of the iOS Notification Center.
version: 1.0.0+1
homepage: https://github.com/flyrboy96
author: Bruce Brookshire <bruce.t.brookshire@gmail.com>

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
